name: "📦 Build Windows C# Application"
on: 
  push:
    branches:
    - "production"

jobs:
  build-windows-x64:
    name: "🔃 BUILD - Build Windows x64"
    runs-on: windows-latest
    
    steps:
      ## Checkout the repository
      - name: "🔃 CI - Checkout the repository"
        uses: actions/checkout@v3
      
      ## Setup the .NET CLI
      - name: "🔃 CI - Setup .NET"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      ## Build the C# Application
      - name: "🔃 CI - Build the C# Application"
        run: |
          dotnet publish  --configuration Release --runtime win-x64 --output out
      - name: "🔃 CI - Upload C# Application"
        uses: actions/upload-artifact@v3
        with:
          name: Windows-x64-Binary
          path: out/CPFValidator.exe

  build-windows-x86:
    name: "🔃 BUILD - Build Windows x86"
    runs-on: windows-latest
    
    steps:
      ## Checkout the repository
      - name: "🔃 CI - Checkout the repository"
        uses: actions/checkout@v3
      
      ## Setup the .NET CLI
      - name: "🔃 CI - Setup .NET"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      ## Build the C# Application
      - name: "🔃 CI - Build the C# Application"
        run: |
          dotnet publish  --configuration Release --runtime  win-x86 --output out
      - name: "🔃 CI - Upload C# Application"
        uses: actions/upload-artifact@v3
        with:
          name: Windows-x86-Binary
          path: out/CPFValidator.exe
  
  build-windows-arm:
    name: "🔃 BUILD - Build Windows ARM"
    runs-on: windows-latest
    
    steps:
      ## Checkout the repository
      - name: "🔃 CI - Checkout the repository"
        uses: actions/checkout@v3
      
      ## Setup the .NET CLI
      - name: "🔃 CI - Setup .NET"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      ## Build the C# Application
      - name: "🔃 CI - Build the C# Application"
        run: |
          dotnet publish  --configuration Release --runtime  win-arm --output out
      - name: "🔃 CI - Upload C# Application"
        uses: actions/upload-artifact@v3
        with:
          name: Windows-ARM-Binary
          path: out/CPFValidator.exe

  build-windows-arm64:
    name: "🔃 BUILD - Build Windows ARM64"
    runs-on: windows-latest
    
    steps:
      ## Checkout the repository
      - name: "🔃 CI - Checkout the repository"
        uses: actions/checkout@v3
      
      ## Setup the .NET CLI
      - name: "🔃 CI - Setup .NET"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      ## Build the C# Application
      - name: "🔃 CI - Build the C# Application"
        run: |
          dotnet publish  --configuration Release --runtime  win-arm64 --output out
      - name: "🔃 CI - Upload C# Application"
        uses: actions/upload-artifact@v3
        with:
          name: Windows-ARM64-Binary
          path: out/CPFValidator.exe